---
- hosts: vb

  vars:
    server_name: cheersbrosnan.com
    symfony_root_dir: /var/www/cheers
    symfony_web_dir: "{{ symfony_root_dir }}/public"
    symfony_console_path: "{{ symfony_root_dir}}/bin/console"

  tasks:
    - ping: ~

    - name: Update ATP package manager repositories cache
      become: true
      apt:
        update_cache: yes

    - name: Upgrade existing packages
      become: true
      apt:
        upgrade: safe

    - name: Install cowsay - it' probably important
      apt:
        name: cowsay
      become: true

    - name: Install low-level utilities
      become: true
      apt:
        name:
          - zip
          - unzip

    - name: Install Git
      become: true
      apt:
        name: git
        state: latest

    - name: Install NGINX
      become: true
      apt:
        name: nginx
        state: latest
      notify: Restart Nginx

    - name: Install MySQL db server
      become: true
      apt:
        name: mysql-server
        state: latest

    - name: Add php 7 PPA repo
      become: true
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install PHP CLI
      become: true
      apt:
        name: php7.2-cli
        state: latest

    - name: Install PHP Packages
      become: true
      apt:
        name:
          - php7.2-cli
          - php7.2-curl
          - php7.2-fpm
          - php7.2-intl
          - php7.2-mysql
          - php7.2-xml
          - php7.2-mbstring
          - php7.2-zip
        state: latest
      notify: Restart PHP-FPM

    - name: Set date.timezone for CLI
      become: true
      lineinfile:
        path: /etc/php/7.2/cli/php.ini
        regexp: "date.timezone ="
        line: "date.timezone = UTC"

    - name: Set date.timezone for FPM
      become: true
      lineinfile:
        path: /etc/php/7.2/fpm/php.ini
        regexp: "date.timezone ="
        line: "date.timezone = UTC"
      notify: Restart PHP-FPM

    - name: Create projectg directory and set its permissions
      become: true
      file:
        path: "{{ symfony_root_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes

    - name: Ceckout Git repo
      git:
        repo: https://github.com/Surf-N-Code/cheers.git
        dest: "{{ symfony_root_dir }}"
        force: yes

    - name: Download composer
      script: scripts/install_composer.sh

    - name: Move composer globally
      become: true
      command: "mv composer.phar /usr/local/bin/composer"

    - name: Set permissons on cmposer
      become: true
      file:
        path: /usr/local/bin/composer
        mode: "a+x"

    - name: Install Composer dependencies
      composer:
        working_dir: "{{ symfony_root_dir }}"
        no_dev: no

    - name: Add Symfony config template to the nginx available sites
      become: true
      template:
        src: templates/symfony.conf
        dest: "/etc/nginx/sites-available/{{ server_name }}.conf"
      notify: Restart Nginx

    - name: Enable symfony config template from nginx available sites
      become: true
      file:
        src: "/etc/nginx/sites-available/{{ server_name }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
        state: link
      notify: Restart Nginx

    - name: Add enabled Nginx site /etc/hosts
      become: true
      lineinfile:
        dest: /etc/hosts
        regexp: "{{ server_name }}"
        line: "127.0.0.1 {{ server_name }}"

    # Symfony console commands
    - name: Create DB if not exists
      command: '{{ symfony_console_path }} doctrine:database:create --if-not-exists'

    - name: Execute migrations
      command: '{{ symfony_console_path }} doctrine:migrations:migrate --no-interaction'

  handlers:
    - name: Restart Nginx
      become: true
      service:
        name: nginx
        state: restarted

    - name: Restart PHP-FPM
      become: true
      service:
        name: php7.2-fpm
        state: restarted